### ISSUE TITLE
Pip Install does not work

### ISSUE THREAD

**Issue by mfarmani95** [mhpi/hydroDL#20]
Hi,
I was trying to install HydroDL using pip install hydroDL command.
But the following error occurred.
I appreciate it if anyone could you help me in this regards
Best Regards,
Mohammad

**Collecting hydroDL
  Using cached hydroDL-0.1.3-py3-none-any.whl (84 kB)
Collecting pandas
  Using cached pandas-1.3.5-cp37-cp37m-macosx_10_9_x86_64.whl (11.0 MB)
Collecting tqdm
  Using cached tqdm-4.66.2-py3-none-any.whl (78 kB)
Collecting statsmodels
  Using cached statsmodels-0.13.5-cp37-cp37m-macosx_10_9_x86_64.whl (9.6 MB)
Collecting torch==1.7.1
  Using cached torch-1.7.1-cp37-none-macosx_10_9_x86_64.whl (108.8 MB)
Collecting matplotlib==3.4.0
  Using cached matplotlib-3.4.0-cp37-cp37m-macosx_10_9_x86_64.whl (7.2 MB)
Collecting numpy
  Using cached numpy-1.21.6-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)
Collecting scipy
  Using cached scipy-1.7.3-cp37-cp37m-macosx_10_9_x86_64.whl (33.0 MB)
Collecting basemap==1.3.0
  Using cached basemap-1.3.0.zip (83 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /private/var/folders/wr/323h4t5x63zbc0d1jr1l1nlm0000gn/T/pip-install-_8uyjww8/basemap_ec1ce07a541d483eb0f70dd618e1d272/setup.py:106: RuntimeWarning: unable to locate NumPy headers
        warnings.warn("unable to locate NumPy headers", RuntimeWarning)
      /private/var/folders/wr/323h4t5x63zbc0d1jr1l1nlm0000gn/T/pip-install-_8uyjww8/basemap_ec1ce07a541d483eb0f70dd618e1d272/setup.py:60: RuntimeWarning: Cannot find GEOS library and/or headers in standard locations ('/Users/mohammad/local', '/Users/mohammad', '/usr/local', '/usr', '/opt/local', '/opt', '/sw'). Please install the corresponding packages using your software management system or set the environment variable GEOS_DIR to point to the location where GEOS is installed (for example, if 'geos_c.h' is in '/usr/local/include' and 'libgeos_c' is in '/usr/local/lib', then you need to set GEOS_DIR to '/usr/local'
        ]).format("', '".join(candidates)), RuntimeWarning)
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/wr/323h4t5x63zbc0d1jr1l1nlm0000gn/T/pip-install-_8uyjww8/basemap_ec1ce07a541d483eb0f70dd618e1d272/setup.py", line 149, in <module>
          dev_requires = get_content("requirements-dev.txt", splitlines=True)
        File "/private/var/folders/wr/323h4t5x63zbc0d1jr1l1nlm0000gn/T/pip-install-_8uyjww8/basemap_ec1ce07a541d483eb0f70dd618e1d272/setup.py", line 23, in get_content
          with io.open(path, encoding="utf-8") as fd:
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/wr/323h4t5x63zbc0d1jr1l1nlm0000gn/T/pip-install-_8uyjww8/basemap_ec1ce07a541d483eb0f70dd618e1d272/requirements-dev.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.**

**Comment by taddyb** [comment]
It looks like this is a basemap issue as Basemap relies on older versions of Matplot lib and we support version 3.8

```

The conflict is caused by:
    hydrodl 0.1.3 depends on matplotlib==3.8.0
    basemap 1.3.2 depends on matplotlib<3.6 and >=1.5; python_version >= "3.5"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by eldia-web** [comment]
Thanks for your response.
I used the instruction on the  HydroDL Github page, 
"conda create -n mhpihydrodl python=3.7
conda activate mhpihydrodl
pip install hydroDL"
I did not specified any package version, how should I do what your are suggesting?

**Comment by taddyb** [comment]
@eldia-web the command `pip install hydroDL` installs hydroDL from PyPi. This is different than using a `git clone`. Installing from pip allows you to use hydroDL and it's functions similar to how NumPy, Pandas, or Xarray are used and makes it so you do not have to put your code inside of the hydroDL repo if you do not want to. 

We've made some developments internally to update hydroDL and it's functions with the latest PyTorch versions, but the PyPi version is lagging. 

While you didn't specify any packages, the dependencies of hydroDL specified by the `setup.py` used to push hydroDL to PyPi is what's causing the problem.

@JiangtaoLiud can comment further if I missed anything

**Comment by JiangtaoLiud** [comment]
@eldia-web We have updated the package, can you try it again?

**Comment by mfarmani95** [comment]
Hi Sorry for late respond.
I tried it again and it is working well.
Thanks for the help.
