### ISSUE TITLE
how to run VIC calibration study?

### ISSUE THREAD

**Issue by daofeng2007** [mhpi/hydroDL#9]
The paper titled "From calibration to parameter learning: Harnessing the scaling effects of big data in geoscientific modeling" pointed me to this place. I want to run the first main case study in that paper that calibrated VIC model. Could you let me know which code example I should use to run that case study?

**Comment by chaopengshen** [comment]
Sorry for the late reply. The following link was available from the "Code Availability" Section of Tsai et al., 2021. 
The code for dPL with example datasets is available from the permanent web archival service Zenodo at https://doi.org/10.5281/zenodo.5227738.
